### PR TITLE
Improve dashboard

### PR DESCRIPTION
**Pull request by SergioAtSUSE**
- add autoyast profile
- represent the expected file system hierarchy

### CODE REVIEW

**Comment by okurz** [comment]
So your idea is to put the .git repo into / instead of a home folder?

**Comment by SergioAtSUSE** [comment]
Not exactly, the git repo can land where the user wants, but I am trying that the git repo represents the expected tree, with the autoinst.xml file unter _/root/_ (like after executing `yast2 clone_system`) and the rest under /home/dashboard/. So the user know where to put each file without reading any documentation.

I have moved the autoinst file to a subfolder to keep it archived adding the date of creation and saved from future `yast2 clone_system` execution, which could delete the file overwriting it.

**Comment by okurz** [comment]
But then I don't understand how you would actually use it. On the one dashboard computer /home/dashboard/ is actually a git working copy. So how would *you* use it then?

**Comment by SergioAtSUSE** [comment]
But then you have to keep everything in home folder.
What happens if, for example, you want to add fstab to git? would you copy the file into the home folder in order to do it?

I don't like the idea of using the home folder as a git repo.
When you install the system with the user dashboard, the home folder will be created with default conf files and scripts, like .bashrc, .profile.
Then when you clone the git repo into an fresh installed system, you have to deal with those existing files. (it is tedious work if you don't want to keep them and even more tedious if you want to keep them, playing with mv, cp and rm...

I would create a bash script that creates symbolic links to the end-files of the cloned repo, so we can still keep track of the changes with minimal effort but not having git directly in home.
I wanted to created it after you confirm that you like these changes, but I will create it and add it to this PR so you can see what I mean.

**Comment by SergioAtSUSE** [comment]
Done, please see https://github.com/okurz/openqa_dashboard/pull/1/commits/b5f9ceb9501d8b5e2a41252016feb7dc3cb79e4a

**Pull request closed without merging**
